services:
  nginx:
    image: nginx:${TAG}
    container_name: nginx
    build:
      context: ./requirements/nginx
      args:
        - WP_DOMAIN_NAME=${WP_DOMAIN_NAME}
    networks:
      - front
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - wp:/var/www/html
    depends_on:
      - wordpress
    restart: always

  wordpress:
    image: wordpress:${TAG}
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    environment:
        - WP_DB_NAME=${WP_DB_NAME}
        - WP_ADMIN=${WP_ADMIN}
        - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
        - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
        - WP_DB_HOST=${DB_HOST}
        - WP_DOMAIN_NAME=${WP_DOMAIN_NAME}
        - WP_DB_CHARSET=${WP_DB_CHARSET}
        - WP_DEBUG=${WP_DEBUG}
    networks:
      - front
      - back
    volumes:
      - wp:/var/www/html
    depends_on:
      - mariadb
    restart: always

  mariadb:
    image: mariadb:${TAG}
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    environment:
      - DB_NAME=${WP_DB_NAME}
      - DB_ADMIN=${WP_ADMIN}
      - DB_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - DB_USER=${WP_USER}
      - DB_USER_PASSWORD=${WP_USER_PASSWORD}
    networks:
      - back
    volumes:
      - db:/var/lib/mysql
    restart: always

volumes:
  wp:
    driver_opts:
      type: none
      o: bind
      device: /Users/sawamurashun/data/wordpress
      # device: /home/${USER}/data/wordpress

  db:
    driver_opts:
      type: none
      o: bind
      device: /Users/sawamurashun/data/mariadb
      # device: /home/${USER}/data/mariadb

networks:
  front:
    driver: bridge
  back:
    driver: bridge
